language: julia
os:
  - linux
  - osx
julia:
  - 0.4
  - nightly
notifications:
  email: false
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia -e 'Pkg.clone("https://github.com/mbauman/RangeArrays.jl.git")'
 - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("RaggedArrays"); Pkg.test("RaggedArrays"; coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("RaggedArrays")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
